from __future__ import annotations

from pathlib import Path
import json
from typing import Any

import joblib
import numpy as np
import pandas as pd
from catboost import CatBoostClassifier, Pool

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
MODEL_DIR = ROOT / "model"

# Fields that can be generated by a return/service workflow. These are excluded
# from any pre-dispatch model even when they are present in historical rows.
LEAKAGE_COLUMNS = ["pickup_scheduled_at", "last_service_event_type"]
RAW_DROP = [
    "order_id",
    "returned",
    "order_placed_at",
    "signup_date",
    "launch_date",
    "pickup_scheduled_at",
    "last_service_event_type",
    "delivery_note",
]

CAT_COLUMNS = [
    "sku",
    "sales_channel",
    "payment_mode",
    "is_gift",
    "source",
    "city",
    "state",
    "shield_member",
    "family",
    "model_name",
]

FRIENDLY = {
    "payment_mode": "payment method",
    "sales_channel": "sales channel",
    "shield_member": "Kestrel Shield membership",
    "customer_prior_returns": "previous returns",
    "customer_prior_orders": "previous orders",
    "prior_return_rate": "historical return rate",
    "sku": "product SKU",
    "family": "product family",
    "model_name": "product model",
    "discount_pct": "checkout discount",
    "promised_delivery_days": "promised delivery window",
    "price_gap": "price vs list price",
    "price_ratio": "price/list-price ratio",
    "order_value_inr": "order value",
    "value_per_unit": "value per unit",
    "warranty_months": "warranty length",
    "order_hour": "order hour",
    "order_month": "order month",
    "order_dow": "day of week",
    "days_since_signup": "customer tenure",
    "days_since_launch": "product age at order",
    "pincode_default": "default delivery pincode",
    "note_len": "delivery note length",
    "note_words": "delivery note word count",
}

NOTE_KEYWORDS = [
    "call",
    "security",
    "weekday",
    "gate",
    "leave",
    "office",
    "landmark",
    "delivery",
    "before",
    "code",
    "whatsapp",
    "care",
    "fragile",
    "handle",
    "wrong",
    "change",
    "model",
    "address",
    "cancel",
    "gift",
    "petrol",
    "pump",
    "bazaar",
    "hp",
    "atm",
    "axis",
    "bank",
]


def load_tables() -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    return (
        pd.read_csv(DATA / "train.csv"),
        pd.read_csv(DATA / "test_unlabelled.csv"),
        pd.read_csv(DATA / "customers.csv"),
        pd.read_csv(DATA / "products.csv"),
    )


def merge_refs(df: pd.DataFrame, customers: pd.DataFrame, products: pd.DataFrame) -> pd.DataFrame:
    out = df.merge(customers, on="customer_id", how="left", validate="many_to_one")
    out = out.merge(products, on="sku", how="left", validate="many_to_one")
    return out


def dedupe_historical(df: pd.DataFrame) -> pd.DataFrame:
    """Remove partner-feed reimports so a duplicated order is not double-weighted."""
    x = df.copy()
    # The source note says partner_outlet orders can be re-imported from partner_feed.
    # For a duplicated order, keep the CRM copy as the canonical row because it is the
    # system-of-record representation; preserve source as a real feature on non-duplicates.
    x["_source_rank"] = x["source"].eq("crm").astype(int)
    x = (
        x.sort_values(["order_id", "_source_rank"], ascending=[True, False])
        .drop_duplicates("order_id", keep="first")
        .drop(columns="_source_rank")
    )
    return x


def _safe_divide(a: pd.Series, b: pd.Series) -> pd.Series:
    a = a.astype(float)
    b = b.astype(float)
    return a.divide(b.where(b.ne(0), np.nan)).fillna(0.0)


def make_features(df: pd.DataFrame) -> pd.DataFrame:
    x = df.copy()
    dt = pd.to_datetime(x["order_placed_at"], errors="coerce")
    signup = pd.to_datetime(x["signup_date"], errors="coerce")
    launch = pd.to_datetime(x["launch_date"], errors="coerce")

    x["order_month"] = dt.dt.month.fillna(0).astype(int)
    x["order_dow"] = dt.dt.dayofweek.fillna(0).astype(int)
    x["order_hour"] = dt.dt.hour.fillna(0).astype(int)
    x["order_day"] = dt.dt.day.fillna(0).astype(int)
    x["days_since_signup"] = (dt - signup).dt.days.clip(lower=0).fillna(0)
    x["days_since_launch"] = (dt - launch).dt.days.clip(lower=0).fillna(0)

    x["prior_return_rate"] = _safe_divide(
        x["customer_prior_returns"], x["customer_prior_orders"]
    )
    x["repeat_customer"] = (x["customer_prior_orders"] > 0).astype(int)
    x["prior_returns_any"] = (x["customer_prior_returns"] > 0).astype(int)
    x["prior_non_return_orders"] = (
        x["customer_prior_orders"] - x["customer_prior_returns"]
    ).clip(lower=0)

    qty = x["qty"].clip(lower=1)
    x["value_per_unit"] = x["order_value_inr"] / qty
    discount_factor = (1 - x["discount_pct"] / 100).clip(lower=0.01)
    implied_full = x["order_value_inr"] / discount_factor
    x["discount_value"] = implied_full - x["order_value_inr"]
    x["price_gap"] = x["order_value_inr"] / qty - x["list_price_inr"]
    x["price_ratio"] = (x["order_value_inr"] / qty) / x["list_price_inr"].clip(lower=1)

    x["pincode_default"] = (x["delivery_pincode"] == 0).astype(int)
    x["pincode_prefix"] = (x["delivery_pincode"] // 1000).astype(str)
    x["pincode_region"] = (x["delivery_pincode"] // 10000).astype(str)

    note = x["delivery_note"].fillna("").astype(str).str.lower()
    x["note_missing"] = note.eq("").astype(int)
    x["note_len"] = note.str.len()
    x["note_words"] = note.str.split().str.len()
    for word in NOTE_KEYWORDS:
        x[f"note_{word}"] = note.str.contains(rf"\b{word}\b", regex=True).astype(int)

    # Cyclical time features are useful to tree/linear components without leaking a date.
    x["hour_sin"] = np.sin(2 * np.pi * x["order_hour"] / 24)
    x["hour_cos"] = np.cos(2 * np.pi * x["order_hour"] / 24)
    x["dow_sin"] = np.sin(2 * np.pi * x["order_dow"] / 7)
    x["dow_cos"] = np.cos(2 * np.pi * x["order_dow"] / 7)

    # Customer ID is deliberately not included as a raw categorical: prior-order and
    # prior-return fields already encode the customer's known history at dispatch.
    return x.drop(columns=RAW_DROP + ["customer_id"], errors="ignore")


def _normalise_categoricals(x: pd.DataFrame, cat_columns: list[str]) -> pd.DataFrame:
    out = x.copy()
    for c in cat_columns:
        if c in out.columns:
            out[c] = out[c].fillna("MISSING").astype(str)
    return out


def fit_catboost(
    X: pd.DataFrame,
    y: pd.Series,
    X_valid: pd.DataFrame | None = None,
    y_valid: pd.Series | None = None,
    iterations: int = 220,
    seed: int = 42,
) -> tuple[CatBoostClassifier, list[str]]:
    cat = [c for c in CAT_COLUMNS if c in X.columns]
    X = _normalise_categoricals(X, cat)
    if X_valid is not None:
        X_valid = _normalise_categoricals(X_valid, cat)

    model = CatBoostClassifier(
        iterations=iterations,
        depth=7,
        learning_rate=0.035,
        loss_function="Logloss",
        eval_metric="AUC",
        verbose=False,
        random_seed=seed,
        l2_leaf_reg=6,
        random_strength=1.0,
        allow_writing_files=False,
    )
    fit_kwargs: dict[str, Any] = {"cat_features": cat, "verbose": False}
    if X_valid is not None and y_valid is not None:
        fit_kwargs.update({"eval_set": (X_valid, y_valid), "use_best_model": True, "early_stopping_rounds": 60})
    model.fit(X, y, **fit_kwargs)
    return model, cat


def prepare_linear_pipeline(X: pd.DataFrame):
    from sklearn.compose import ColumnTransformer
    from sklearn.impute import SimpleImputer
    from sklearn.linear_model import LogisticRegression
    from sklearn.pipeline import Pipeline
    from sklearn.preprocessing import OneHotEncoder, StandardScaler

    cats = X.select_dtypes(include="object").columns.tolist()
    nums = [c for c in X.columns if c not in cats]
    pre = ColumnTransformer(
        [
            (
                "cat",
                OneHotEncoder(handle_unknown="ignore", min_frequency=3),
                cats,
            ),
            (
                "num",
                Pipeline(
                    [
                        ("impute", SimpleImputer(strategy="median")),
                        ("scale", StandardScaler()),
                    ]
                ),
                nums,
            ),
        ],
        remainder="drop",
    )
    pipe = Pipeline(
        [
            ("preprocess", pre),
            ("classifier", LogisticRegression(max_iter=2500, C=0.2)),
        ]
    )
    return pipe


def friendly_reason(feature: str, value: Any) -> str:
    if feature.startswith("note_"):
        word = feature.removeprefix("note_")
        if word == "missing":
            return "No delivery note was supplied"
        if feature == "note_len":
            return f"Delivery note length is {int(value)} characters"
        if feature == "note_words":
            return f"Delivery note contains {int(value)} words"
        if int(value) == 1:
            return f"Delivery note mentions “{word}”"
    if feature == "pincode_default" and int(value) == 1:
        return "The delivery address uses the system-default pincode"
    if feature == "prior_return_rate":
        return f"Historical return rate is {float(value):.1%}"
    if feature == "price_gap":
        return f"Price per unit differs from list price by ₹{float(value):,.0f}"
    if feature == "price_ratio":
        return f"Price is {float(value):.0%} of list price"
    if feature == "discount_pct":
        return f"Checkout discount is {float(value):.0f}%"
    if feature == "promised_delivery_days":
        return f"Promised delivery window is {int(value)} days"
    if feature == "payment_mode":
        return f"Payment mode is {value}"
    if feature == "sales_channel":
        return f"Sales channel is {value}"
    if feature == "shield_member":
        return f"Shield membership is {value}"
    if feature in {"customer_prior_returns", "customer_prior_orders", "prior_non_return_orders"}:
        return f"{FRIENDLY.get(feature, feature)} = {int(value)}"
    if feature == "order_hour":
        return f"Order was placed around {int(value):02d}:00"
    if feature == "days_since_signup":
        return f"Customer tenure is about {int(value)} days"
    if feature == "days_since_launch":
        return f"Product age at order is about {int(value)} days"
    if feature == "value_per_unit":
        return f"Value per unit is ₹{float(value):,.0f}"
    if feature in {"family", "model_name", "sku", "city", "state", "source", "is_gift"}:
        return f"{FRIENDLY.get(feature, feature.replace('_', ' ')).capitalize()} is {value}"
    return f"{FRIENDLY.get(feature, feature.replace('_', ' ')).capitalize()} = {value}"


def catboost_reasons(model: CatBoostClassifier, Xrow: pd.DataFrame, cat: list[str], top_n: int = 3) -> list[dict[str, Any]]:
    pool = Pool(_normalise_categoricals(Xrow, cat), cat_features=cat)
    shap = model.get_feature_importance(pool, type="ShapValues")[0, :-1]
    vals = Xrow.iloc[0]
    order = np.argsort(np.abs(shap))[::-1]
    out = []
    for idx in order:
        feature = Xrow.columns[idx]
        value = vals[feature]
        if feature in {"pincode_prefix", "pincode_region", "hour_sin", "hour_cos", "dow_sin", "dow_cos"}:
            continue
        out.append(
            {
                "feature": feature,
                "impact": float(shap[idx]),
                "direction": "increases risk" if shap[idx] > 0 else "reduces risk",
                "reason": friendly_reason(feature, value),
                "model": "CatBoost",
            }
        )
        if len(out) >= top_n:
            break
    return out


def logistic_reasons(model, Xrow: pd.DataFrame, top_n: int = 3) -> list[dict[str, Any]]:
    pre = model.named_steps["preprocess"]
    clf = model.named_steps["classifier"]
    transformed = pre.transform(Xrow)
    dense = transformed.toarray()[0] if hasattr(transformed, "toarray") else np.asarray(transformed)[0]
    coeff = clf.coef_[0]
    feature_names = pre.get_feature_names_out()
    contributions = dense * coeff
    order = np.argsort(np.abs(contributions))[::-1]
    out = []
    for idx in order:
        if abs(contributions[idx]) < 0.01:
            continue
        name = feature_names[idx]
        clean = name.split("__", 1)[-1]
        value = dense[idx]
        if clean in Xrow.columns:
            reason = friendly_reason(clean, Xrow.iloc[0][clean])
        elif clean.startswith("note_"):
            label = clean.removeprefix("note_")
            reason = f"Delivery note mentions \"{label.replace('_', ' ')}\""
        else:
            # One-hot categorical feature names typically look like payment_mode_cod.
            parts = clean.rsplit("_", 1)
            if len(parts) == 2 and parts[0] in FRIENDLY:
                reason = f"{FRIENDLY[parts[0]].capitalize()} is {parts[1]}"
            else:
                reason = clean.replace("_", " ").capitalize()
        out.append(
            {
                "feature": clean,
                "impact": float(contributions[idx]),
                "direction": "increases risk" if contributions[idx] > 0 else "reduces risk",
                "reason": reason,
                "model": "Logistic regression",
                "raw_value": float(value),
            }
        )
        if len(out) >= top_n:
            break
    return out


def load_artifacts() -> tuple[CatBoostClassifier, Any, dict[str, Any]]:
    cat = CatBoostClassifier()
    cat.load_model(str(MODEL_DIR / "kestrel_catboost.cbm"))
    linear = joblib.load(MODEL_DIR / "kestrel_logistic.joblib")
    meta = json.loads((MODEL_DIR / "metadata.json").read_text())
    return cat, linear, meta


def predict_dataframe(X: pd.DataFrame, cat_model, linear_model, meta: dict[str, Any]) -> np.ndarray:
    X = X[meta["feature_columns"]].copy()
    cat_x = _normalise_categoricals(X, meta["cat_columns"])
    p_cat = cat_model.predict_proba(cat_x)[:, 1]
    p_lin = linear_model.predict_proba(X)[:, 1]
    return meta["blend_weight_catboost"] * p_cat + meta["blend_weight_logistic"] * p_lin
